test fix retry

diff --git a/.github/workflows/CD.yml b/.github/workflows/CD.yml
--- a/.github/workflows/CD.yml
+++ b/.github/workflows/CD.yml
@@ -13,7 +13,7 @@
 
 name: C/D
 
-on:        
+on:
   workflow_dispatch:
     inputs:
       version:
@@ -22,7 +22,7 @@ on:
       sha:
         description: 'the github sha to release'
         required: true
-    
+
 env:
   IMAGE_NAME: aws-otel-collector
   IMAGE_NAMESPACE: amazon
@@ -41,12 +41,12 @@ env:
   RELEASE_S3_BUCKET: "aws-otel-collector"
 
 jobs:
-  release-checking: 
+  release-checking:
     runs-on: ubuntu-latest
     outputs:
       version: ${{ steps.checking_sha_version.outputs.version }}
       testing_version: ${{ steps.checking_sha_version.outputs.testing_version }}
-    steps: 
+    steps:
       - uses: actions/checkout@v2
 
       - name: Configure AWS Credentials
@@ -70,7 +70,7 @@ jobs:
           sha_in_candidate=`cat $PACKAGING_ROOT/GITHUB_SHA`
 
           if [ $version_in_release != ${{ github.event.inputs.version }} ]; then
-            echo "::error::Wrong version is detected: $version_in_candidate != ${{ github.event.inputs.version }}"
+            echo "::error::Wrong version is detected: $version_in_release != ${{ github.event.inputs.version }}"
             exit 1
           fi
           if [ $sha_in_candidate != ${{ github.event.inputs.sha }} ]; then
@@ -100,13 +100,13 @@ jobs:
         uses: actions/checkout@v2
         with:
           ref: ${{ github.event.inputs.sha }}
-      
+
       - name: Setup Python
         uses: actions/setup-python@v2.3.1
 
       - name: Get all the testing suites
         id: set-matrix
-        run: | 
+        run: |
           ec2_matrix_1=$(python e2etest/get-testcases.py ec2_matrix_1)
           ec2_matrix_2=$(python e2etest/get-testcases.py ec2_matrix_2)
           ec2_matrix_3=$(python e2etest/get-testcases.py ec2_matrix_3)
@@ -124,7 +124,7 @@ jobs:
           echo ${{ steps.set-matrix.outputs.ec2-matrix-1 }}
           echo ${{ steps.set-matrix.outputs.ec2-matrix-2 }}
           echo ${{ steps.set-matrix.outputs.ec2-matrix-3 }}
-          
+
   release-to-s3:
     runs-on: ubuntu-latest
     needs: [release-checking]
@@ -150,16 +150,16 @@ jobs:
       #Create ssm package and binaries/artifacts for validation test which is similar to SSM workflow release
       - name: Create SSM packages for validation test and set permission to public
         run: |
-            ( aws ssm describe-document --name ${{ env.SSM_RELEASE_PACKAGE_NAME }} --version-name ${{ needs.release-checking.outputs.version }} >/dev/null 2>&1 ) || {
-                  pip3 install boto3
-                  python3 tools/ssm/ssm_manifest.py ${{ needs.release-checking.outputs.version }}
-                  aws s3 cp $PACKAGING_ROOT/ssm s3://${{ env.SSM_RELEASE_S3_BUCKET }}/ssmfile/${{ needs.release-checking.outputs.version }} --recursive
-                  python3 tools/ssm/ssm_create.py ${{ env.SSM_RELEASE_PACKAGE_NAME }} ${{ needs.release-checking.outputs.version }} ${{ env.SSM_RELEASE_S3_BUCKET }}/ssmfile/${{ needs.release-checking.outputs.version }} us-west-2
-                  aws --region us-west-2 ssm modify-document-permission \
-                      --name ${{ env.SSM_RELEASE_PACKAGE_NAME }} \
-                      --permission-type "Share" \
-                      --account-ids-to-add "All"
-            }
+          ( aws ssm describe-document --name ${{ env.SSM_RELEASE_PACKAGE_NAME }} --version-name ${{ needs.release-checking.outputs.version }} >/dev/null 2>&1 ) || {
+                pip3 install boto3
+                python3 tools/ssm/ssm_manifest.py ${{ needs.release-checking.outputs.version }}
+                aws s3 cp $PACKAGING_ROOT/ssm s3://${{ env.SSM_RELEASE_S3_BUCKET }}/ssmfile/${{ needs.release-checking.outputs.version }} --recursive
+                python3 tools/ssm/ssm_create.py ${{ env.SSM_RELEASE_PACKAGE_NAME }} ${{ needs.release-checking.outputs.version }} ${{ env.SSM_RELEASE_S3_BUCKET }}/ssmfile/${{ needs.release-checking.outputs.version }} us-west-2
+                aws --region us-west-2 ssm modify-document-permission \
+                    --name ${{ env.SSM_RELEASE_PACKAGE_NAME }} \
+                    --permission-type "Share" \
+                    --account-ids-to-add "All"
+          }
 
   s3-release-validation-1:
     runs-on: ubuntu-latest
@@ -211,14 +211,19 @@ jobs:
       - name: Run testing suite on ec2
         if: steps.s3-release-validation-1.outputs.cache-hit != 'true'
         run: |
-          if [[ -f testing-framework/terraform/testcases/${{ matrix.testcase }}/parameters.tfvars ]] ; then opts="-var-file=../testcases/${{ matrix.testcase }}/parameters.tfvars" ; else opts="" ; fi
+          opts=""
+          if [[ -f testing-framework/terraform/testcases/${{ matrix.testcase }}/parameters.tfvars ]] ; then opts="-var-file=../testcases/${{ matrix.testcase }}/parameters.tfvars" ; fi
           cd testing-framework/terraform/ec2 && terraform init && terraform apply -auto-approve -lock=false $opts -var="testing_ami=${{ matrix.testing_ami }}" -var="aoc_version=${{ needs.release-checking.outputs.version }}" -var="package_s3_bucket=${{ env.RELEASE_S3_BUCKET }}" -var="testcase=../testcases/${{ matrix.testcase }}" -var="ssm_package_name=${{ env.SSM_RELEASE_PACKAGE_NAME }}"
-          
+
       - name: Destroy resources
         if: ${{ always() && steps.s3-release-validation-1.outputs.cache-hit != 'true' }}
-        run: |
-          cd testing-framework/terraform/ec2 && terraform destroy -auto-approve
-          
+        uses: nick-invision/retry@v2
+        with:
+          max_attempts: 3
+          timeout_minutes: 8
+          retry_wait_seconds: 20
+          command: cd testing-framework/terraform/ec2 && terraform destroy -auto-approve
+
   s3-release-validation-2:
     runs-on: ubuntu-latest
     needs: [get-testing-suites, release-to-s3, release-checking]
@@ -269,14 +274,19 @@ jobs:
       - name: Run testing suite on ec2
         if: steps.s3-release-validation-2.outputs.cache-hit != 'true'
         run: |
-          if [[ -f testing-framework/terraform/testcases/${{ matrix.testcase }}/parameters.tfvars ]] ; then opts="-var-file=../testcases/${{ matrix.testcase }}/parameters.tfvars" ; else opts="" ; fi
+          opts=""
+          if [[ -f testing-framework/terraform/testcases/${{ matrix.testcase }}/parameters.tfvars ]] ; then opts="-var-file=../testcases/${{ matrix.testcase }}/parameters.tfvars" ; fi
           cd testing-framework/terraform/ec2 && terraform init && terraform apply -auto-approve -lock=false $opts -var="testing_ami=${{ matrix.testing_ami }}" -var="aoc_version=${{ needs.release-checking.outputs.version }}" -var="package_s3_bucket=${{ env.RELEASE_S3_BUCKET }}" -var="testcase=../testcases/${{ matrix.testcase }}" -var="ssm_package_name=${{ env.SSM_RELEASE_PACKAGE_NAME }}"
-          
+
       - name: Destroy resources
         if: ${{ always() && steps.s3-release-validation-2.outputs.cache-hit != 'true' }}
-        run: |
-          cd testing-framework/terraform/ec2 && terraform destroy -auto-approve
-          
+        uses: nick-invision/retry@v2
+        with:
+          max_attempts: 3
+          timeout_minutes: 8
+          retry_wait_seconds: 20
+          command: cd testing-framework/terraform/ec2 && terraform destroy -auto-approve
+
   s3-release-validation-3:
     runs-on: ubuntu-latest
     needs: [get-testing-suites, release-to-s3, release-checking]
@@ -327,14 +337,19 @@ jobs:
       - name: Run testing suite on ec2
         if: steps.s3-release-validation-3.outputs.cache-hit != 'true'
         run: |
-          if [[ -f testing-framework/terraform/testcases/${{ matrix.testcase }}/parameters.tfvars ]] ; then opts="-var-file=../testcases/${{ matrix.testcase }}/parameters.tfvars" ; else opts="" ; fi
+          opts=""
+          if [[ -f testing-framework/terraform/testcases/${{ matrix.testcase }}/parameters.tfvars ]] ; then opts="-var-file=../testcases/${{ matrix.testcase }}/parameters.tfvars" ; fi
           cd testing-framework/terraform/ec2 && terraform init && terraform apply -auto-approve -lock=false $opts -var="testing_ami=${{ matrix.testing_ami }}" -var="aoc_version=${{ needs.release-checking.outputs.version }}" -var="package_s3_bucket=${{ env.RELEASE_S3_BUCKET }}" -var="testcase=../testcases/${{ matrix.testcase }}" -var="ssm_package_name=${{ env.SSM_RELEASE_PACKAGE_NAME }}"
-          
+
       - name: Destroy resources
         if: ${{ always() && steps.s3-release-validation-3.outputs.cache-hit != 'true' }}
-        run: |
-          cd testing-framework/terraform/ec2 && terraform destroy -auto-approve
-          
+        uses: nick-invision/retry@v2
+        with:
+          max_attempts: 3
+          timeout_minutes: 8
+          retry_wait_seconds: 20
+          command: cd testing-framework/terraform/ec2 && terraform destroy -auto-approve
+
   release-version-image:
     runs-on: ubuntu-latest
     needs: [release-checking]
@@ -371,7 +386,7 @@ jobs:
       fail-fast: false
       max-parallel: 5
       matrix: ${{ fromJson(needs.get-testing-suites.outputs.ecs-matrix) }}
-    
+
     steps:
       - uses: actions/checkout@v2
 
@@ -390,38 +405,43 @@ jobs:
           aws-access-key-id: ${{ secrets.INTEG_TEST_AWS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.INTEG_TEST_AWS_KEY_SECRET }}
           aws-region: us-west-2
-          
+
       - name: Set up JDK 11
         if: steps.release-validation-ecs.outputs.cache-hit != 'true'
         uses: actions/setup-java@v2
         with:
           distribution: 'zulu'
           java-version: '11'
-      
+
       - name: Set up terraform
         if: steps.release-validation-ecs.outputs.cache-hit != 'true'
         uses: hashicorp/setup-terraform@v1
         with:
           terraform_version: 0.14.10
-      
+
       - name: Check out testing framework
         if: steps.release-validation-ecs.outputs.cache-hit != 'true'
         uses: actions/checkout@v2
         with:
           repository: "${{ env.TESTING_FRAMEWORK_REPO }}"
           path: testing-framework
-          
+
       - name: Run testing suite on ecs
         if: steps.release-validation-ecs.outputs.cache-hit != 'true'
         run: |
-          if [[ -f testing-framework/terraform/testcases/${{ matrix.testcase }}/parameters.tfvars ]] ; then opts="-var-file=../testcases/${{ matrix.testcase }}/parameters.tfvars" ; else opts="" ; fi
+          opts=""
+          if [[ -f testing-framework/terraform/testcases/${{ matrix.testcase }}/parameters.tfvars ]] ; then opts="-var-file=../testcases/${{ matrix.testcase }}/parameters.tfvars" ; fi
           cd testing-framework/terraform/ecs && terraform init && terraform apply -auto-approve -lock=false $opts -var="ecs_launch_type=${{ matrix.launch_type }}" -var="aoc_version=${{ needs.release-checking.outputs.version }}" -var="aoc_image_repo=$IMAGE_LINK" -var="testcase=../testcases/${{ matrix.testcase }}"
-                    
+
       - name: Destroy resources
         if: ${{ always() && steps.release-validation-ecs.outputs.cache-hit != 'true' }}
-        run: |
-          cd testing-framework/terraform/ecs && terraform destroy -auto-approve           
-                  
+        uses: nick-invision/retry@v2
+        with:
+          max_attempts: 3
+          timeout_minutes: 8
+          retry_wait_seconds: 20
+          command: cd testing-framework/terraform/ecs && terraform destroy -auto-approve
+
   release-validation-eks:
     runs-on: ubuntu-latest
     needs: [get-testing-suites, release-version-image, release-checking]
@@ -429,7 +449,7 @@ jobs:
       fail-fast: false
       max-parallel: 5
       matrix: ${{ fromJson(needs.get-testing-suites.outputs.eks-matrix) }}
-    
+
     steps:
       - uses: actions/checkout@v2
 
@@ -448,37 +468,44 @@ jobs:
           aws-access-key-id: ${{ secrets.INTEG_TEST_AWS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.INTEG_TEST_AWS_KEY_SECRET }}
           aws-region: us-west-2
-          
+
       - name: Set up JDK 11
         if: steps.release-validation-eks.outputs.cache-hit != 'true'
         uses: actions/setup-java@v2
         with:
           distribution: 'zulu'
           java-version: '11'
-      
+
       - name: Set up terraform
         if: steps.release-validation-eks.outputs.cache-hit != 'true'
         uses: hashicorp/setup-terraform@v1
         with:
           terraform_version: 0.14.10
-      
+
       - name: Check out testing framework
         if: steps.release-validation-eks.outputs.cache-hit != 'true'
         uses: actions/checkout@v2
         with:
           repository: "${{ env.TESTING_FRAMEWORK_REPO }}"
           path: testing-framework
-      
+
       - name: Run testing suite on eks
         if: steps.release-validation-eks.outputs.cache-hit != 'true'
         run: |
-          if [[ -f testing-framework/terraform/testcases/${{ matrix.testcase }}/parameters.tfvars ]] ; then opts="-var-file=../testcases/${{ matrix.testcase }}/parameters.tfvars" ; else opts="" ; fi
+          opts=""
+          if [[ -f testing-framework/terraform/testcases/${{ matrix.testcase }}/parameters.tfvars ]] ; then opts="-var-file=../testcases/${{ matrix.testcase }}/parameters.tfvars" ; fi
           cd testing-framework/terraform/eks && terraform init && terraform apply -auto-approve -lock=false $opts -var="aoc_version=${{ needs.release-checking.outputs.version }}" -var="aoc_image_repo=$IMAGE_LINK" -var="testcase=../testcases/${{ matrix.testcase }}"
-          
+
       - name: Destroy resources
         if: ${{ always() && steps.release-validation-eks.outputs.cache-hit != 'true' }}
-        run: |
-          cd testing-framework/terraform/eks && terraform destroy -auto-approve
+        uses: nick-invision/retry@v2
+        with:
+          max_attempts: 3
+          timeout_minutes: 8
+          retry_wait_seconds: 20
+          command: |
+            cd testing-framework/terraform/eks 
+            if terraform destroy -auto-approve; then exit 0; fi
 
   delete-images-binaries-if-fail:
     runs-on: ubuntu-latest
